require("dotenv").config({ path: "../.env" });
const { test, expect } = require("@playwright/test");

/**
🐛 After creating a new post in a group, the client doesn't re-direct to the newly created post

Steps to replicate:

1) log in to any account
2) click "Groups", and select any of the listed groups
3) click "submit a new post"
4) fill title/body
5) click "create post"
6) client is re-directed to an undefined url. the post is still created, however.
 */

test("client successfully redirects to newly created post on submission", async ({ page }) => {
  // initialize app, log in
  await page.goto("http://localhost:3000/");
  await page.getByTestId("nav-login").click();

  await page.getByTestId("username").type(process.env.TEST_USER_USERNAME);
  await page.getByTestId("password").type(process.env.TEST_USER_PASSWORD);

  await page.getByTestId("login-btn").click();

  await expect(page).toHaveURL("http://localhost:3000/"); // confirms successful login

  // navigate to groups
  await page.getByTestId("groups-link").click();
  await expect(page).toHaveURL("http://localhost:3000/groups");

  // select first group
  await page.getByTestId("group-link-0").click();
  await expect(page).toHaveURL(/^http:\/\/localhost:3000\/groups\/\d+$/);

  // get group identifier (name)
  const groupIdentifier = page
    .url()
    .split("/")
    .slice(-1)[0];

  // submit a new post
  await page.getByTestId("create-post-button").click();
  await expect(page).toHaveURL(/^http:\/\/localhost:3000\/create\?group=\d+$/);

  await page.getByTestId("title").type("test post");
  await page.getByTestId("content").type("test post generated by Playwright");
  await page.getByTestId("create-post-btn").click();

  // assert redirection to newly created post. url has the form /groups/identifier/postID
  await expect(page).toHaveURL(
    new RegExp(`^http://localhost:3000/groups/${groupIdentifier}/(\\d+)$`)
  );
});
